apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-1
  name: kafka-1
spec:
  selector:
    matchLabels:
      app: kafka-1
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "MACHINE_IP"
        - name: KAFKA_ADVERTISED_PORT
          value: "30093"
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service.default.svc.cluster.local:2181
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-1
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service-1
  name: kafka-service-1
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 9092
    nodePort: 30093
    targetPort: 9092
  selector:
    app: kafka-1